const CONSTANTS = {
  MODULE_NAME: 'conditional-visibility',
  FLAG_NAME: 'data',
  PATH: `modules/conditional-visibility/`,
  PILE_DEFAULTS: {
    enabled: true,
    distance: 1,
    visibiliyTypeFilters: '',
    overrideAttributes: false,
    canInspectItems: true,
    macro: '',
    deleteWhenEmpty: 'default',
    displayOne: true,
    overrideSingleItemScale: true,
    singleItemScale: 0.75,
    isContainer: false,
    closed: false,
    locked: false,
    closedImage: '',
    emptyImage: '',
    openedImage: '',
    lockedImage: '',
    closeSound: '',
    openSound: '',
    lockedSound: '',
    unlockedSound: '',
  },
};

export default CONSTANTS;
